### ISSUE TITLE
In RStudio: R crashes after using fst::read

### ISSUE THREAD

**Issue by jzzcutler** [fstpackage/fst#100] opened 2017-10-31 21:28 UTC
I really like this package! It is 3 to 10 times faster than readRDS/saveRDS - though compress=100 gives a file about 1.4 times larger than the RDS.  Anyway, as I'm testing this out for the first time under RStudio with all commands wrapped in system.time(), R is repeatedly crashing so that RStudio says "Unable to establish a session with R".  The crash does not appear to happen during the execution of the command.  The error pops up a short while after using an fst command.

The object is a data.table with a key consisting of two integer columns.  All columns are integer.  object.size=3542787088 bytes and dim=892816x498

RStudio=Version 1.0.143
Microsoft R Open 3.4.1 with MKL

**Comment by MarcusKlik** [comment] 2017-10-31 21:38
Hi @jzzcutler, thanks for reporting your issue and good to hear that you like `fst`! I will try to reproduce your problem with random data, did you try running your code without `RStudio` (just using `R` from the command line) ?

**Comment by MarcusKlik** [comment] 2017-10-31 22:27
Hi again @jzzcutler, I've tested reading and writing a `integer`-only `fst` table with dimensions 892816 x 498 with the `dev` version of `fst`:

``` r
nr_of_rows <- 892816
nr_of_cols <- 498
sample_data <- function(x) { sample(1L:1000L, nr_of_rows, replace = TRUE) }

bench <- NULL
for (runID in 1:10) {
  dt <- data.table::data.table(ID = sample_data())

  cat(".")
  for (col_nr in 1:nr_of_cols) {
    dt[, c(paste("Col", col_nr, sep = "")) := sample_data()]
  }

  # set random dual key
  setkeyv(dt, colnames(dt)[sample(1:ncol(dt), 2)])

  # write benchmark
  file_name <- paste(runID, ".fst", sep = "")
  bench <- c(bench, microbenchmark::microbenchmark(
    fst::write_fst(dt, file_name, compress = 50),
    times = 1
  )$time)
}
#> ..........

# write speed
as.numeric(object.size(dt)) / median(bench)
#> [1] 1.549839

bench <- NULL
for (runID in 1:10) {
  cat(".")

  # read benchmark
  file_name <- paste(runID, ".fst", sep = "")
  bench <- c(bench, microbenchmark::microbenchmark(
    fst::read_fst(file_name),
    times = 1
  )$time)
}
#> ..........

# read speed
as.numeric(object.size(dt)) / median(bench)
#> [1] 0.7635682

# verify keys
dt_read <- fst::read_fst("5.fst", as.data.table = TRUE)
key(dt_read)
#> [1] "Col163" "Col337"
```

everything seems to run without problems, could you try your code using the `dev` version?

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

thanks!

**Comment by MarcusKlik** [comment] 2017-10-31 22:41
Hi @jzzcutler, just to be sure, I've done the benchmark on `MS R Open 3.4.2` as well with identical results (on Windows 10).

(and the timings are comparable, `fst` doesn't benefit from the `MKL` libraries)

thanks for testing!

**Comment by xiaodaigh** [comment] 2017-11-08 01:31
I find that if I `Sys.sleep(1)` right after a `read.fst` or `write.fst` then it doesn't crash (as much).

**Comment by MarcusKlik** [comment] 2017-11-08 10:18
Hi @xiaodaigh and @jzzcutler, thanks for reporting, are you still getting crashes then, also on the latest `dev` version?

For example, if you run the benchmark [above](https://github.com/fstpackage/fst/issues/100#issuecomment-340926233) using the latest `fst` development version, are you getting errors (without using `Sys.sleep`)?

**Comment by xiaodaigh** [comment] 2017-11-23 21:15
@jzzcutler I updated to the latest version of fst and I don't encounter issues any more.

These are the steps I followed to get it working.

1. Remove the existing fst package (if you don't do this then you will run into error on Windows)
2. Install using `devtools::install_github("fstpackage/fst")`

Everything works! 

Otherwise, after step 1, you can clone the package and install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) (assuming you are using Windows) and the use the Build tab in Rstudio to build the package from scratch.

**Comment by MarcusKlik** [comment] 2017-11-24 10:35
great, thanks for reporting!

**Comment by thierrygosselin** [comment] 2018-01-15 18:43
is there a fix for RStudio crashing all the time with macOS and fst ?

**Comment by MarcusKlik** [comment] 2018-01-15 21:04
Hi @thierrygosselin, thanks for reporting your problem. When exactly does your system crash, is there a specific code example that causes the crash or are you having crashes when loading the package?

**Comment by MarcusKlik** [comment] 2018-01-15 21:36
Hi @thierrygosselin, just to check, are you experiencing problems on a `fst` dev version build` from source or are you using the CRAN pre-compiled binary version?

**Comment by thierrygosselin** [comment] 2018-01-15 22:26
Both dev version from GitHub and CRAN results in RStudio crashing.
macOS: 10.13.2 (latest)
RStudio: 1.1.383 (latest)
R: 3.4.3 (latest)

**Comment by MarcusKlik** [comment] 2018-01-16 10:49
Hi @thierrygosselin, thanks for the information. So you try to use the _install_ button in RStudio and then it crashes upon installation of the package? And if you type `install.packages("fst")` in the console it doesn't crash? Is there any error message at the time of crashing?

**Comment by Giqles** [comment] 2018-01-22 09:18
I've had a similar problem. In my environment (R 3.4.2, RStudio v0.99), `fst_read` sometimes hangs for a long while then the R process restarts. RStudio itself doesn't crash for me.

**Comment by thierrygosselin** [comment] 2018-01-22 19:05
Hi @MarcusKlik I tested a couple of things:
1. the problem of crashing RStudio/R session is really restricted when the package is used inside another package. No problem using `fst` on it's own.

2. using the _install_ button in RStudio,  `install.packages("fst")` or `devtools::install_github("fstPackage/fst", ref = "develop")` all work for me in macOS.

**Comment by thierrygosselin** [comment] 2018-01-22 19:11
More details here:
1. using the 3 ways to install `fst` ( _install_ button in RStudio, `install.packages("fst")` or `devtools::install_github("fstPackage/fst", ref = "develop")` ) as no impact, they all make RStudio crash if at some point you try to check your package that contains `fst`.

2. All this is new behaviour. I've had `fst` inside my package for quite some time and never experience this problem.

3. Removing `fst` from the _Imports_ package in the _DESCRIPTION_ file fixes my issues with crashing.

I'm open to do some more tests if it can help you resolve the problem

**Comment by thierrygosselin** [comment] 2018-01-22 19:21
Removing `fst` from the _DESCRIPTION_ file still make RStudio crash if the _NAMESPACE_ file is not changed accordingly. To stop crashing, in my case, I have to rebuild the file or erase `importFrom(fst,read.fst)` and `importFrom(fst,write.fst)`

**Comment by PeteHaitch** [comment] 2018-01-22 19:35
@thierrygosselin Yours sounds like the same issue as https://github.com/fstpackage/fst/issues/109. FYI, if you're using **fst** in your package then it needs to be in both the `DESCRIPTION` and `NAMESPACE`, so you won't be able to work around this issue that way by selectively removing it from one.

**Comment by thierrygosselin** [comment] 2018-01-22 19:39
@PeteHaitch Well... you can still have `fst` in the _DESCRIPTION_ file under the _Suggests_ section, and this way it doesn't appear in the _NAMESPACE_ file. But there is no issue doing this.

**Comment by thierrygosselin** [comment] 2018-01-22 19:47
Using `#' @importFrom fst read.fst write.fst` or `#' @import fst` in the function doc that uses `fst` and rebuilding the _NAMESPACE_ file both crash RStudio

**Comment by PeteHaitch** [comment] 2018-01-22 19:51
> Using `#' @importFrom fst read.fst write.fst` or `#' @import fst` in the function doc that uses `fst` and rebuilding the NAMESPACE file both crash RStudio

Yes, I believe that happens for the reason in https://github.com/fstpackage/fst/issues/109#issuecomment-356432371, namely that RStudio launches a new R process to run `devtools::document()` (which I'm guessing you're using to rebuild the `NAMESPACE` via either the keyboard shortcut or button in RStudio). My (limited) understanding is that this is triggering some nasty interaction between OpenMP and forks on macOS that ultimately causes the crash in RStudio.

**Comment by thierrygosselin** [comment] 2018-01-22 20:07
So no fix for this ?

**Comment by thierrygosselin** [comment] 2018-01-22 20:12
I did have a similar issue with `data.table` a couple of months ago.

**Comment by thierrygosselin** [comment] 2018-01-22 20:19
For reproducibility purposes here is the **clang** version (latest) I'm using with macOS (that support OpenMP) and how it was installed. Also, the `~/.R/Makevars` attributes used.

```
$ clang -v
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /usr/local/bin
```

**Installed with these command:**

```
wget http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz
sudo tar -xzvf clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz -C/usr/local --strip-components 1
```

The RStudio crashing issue with `fst` is not related to updating from clang v.5.0.0 to v.5.0.1


**.Makevars**

```
CC=/usr/local/bin/clang
CXX=/usr/local/bin/clang++
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/lib -Wl,-rpath,/usr/local/bin/lib
CPPFLAGS=-I/usr/local/include
```

**Comment by MarcusKlik** [comment] 2018-01-22 21:59
Hi @PeteHaitch and @thierrygosselin, thanks for all the information. This particular problem really puzzles me:

* In `data.table`, the solution to the crashes in RStudio on MacOS seem to be solved as indicated [here](https://github.com/Rdatatable/data.table/issues/2418#ref-commit-9d1f3e2). 
* Before that commit, `data.table` was calling `omp_set_num_threads`, as can be seen [here](https://github.com/Rdatatable/data.table/blob/70db3e48738026388c6487e83ee902ad37256ca5/src/openmp-utils.c#L65)
* After the fix, `omp_set_num_threads` is not called at the fork anymore, see [here](https://github.com/Rdatatable/data.table/blob/master/src/openmp-utils.c#L80).

* In `fst`, method `SetFstThreads` (from `fstlib`) is called [at the fork](https://github.com/fstpackage/fst/blob/develop/src/openmp.cpp#L59).
* That method can be found [here](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/openmphelper.cpp#L47). It doesn't call `omp_set_num_threads` as per the `data.table` solution. But it [does call](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/openmphelper.cpp#L38) `omp_get_max_threads()`.
* Perhaps calling that method from the OpenMP library is causing the same problems as `omp_set_num_threads`, although I can't find an explanation anywhere why that should be a problem (multiple versions of the linked OpenMP library?). But we can certainly try what happens when we don't call that method from the actual fork!

Thanks for all the testing, much obliged!

**Comment by MarcusKlik** [comment] 2018-01-22 22:45
Hi @PeteHaitch and @thierrygosselin, I've just pushed a commit where `omp_get_max_threads()` is not called at the fork anymore (or any other OpenMP method). Instead, only a [global variable is set](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/openmphelper.cpp#L54-L57), just like in the `data.table` package.

OpenMP library calls are still made from the `.onAttach` method, but that is only triggered when you actually use `library` or ` attachNamespace` to attach the `fst` package, not when a fork is made.

I can't reproduce the error myself but if you would be willing to test again with the latest `dev` version of `fst`, that would be great, thanks a lot!

**Comment by PeteHaitch** [comment] 2018-01-22 22:57
Good news!!! After installing https://github.com/fstpackage/fst/commit/b6eadb4f6f910e7e1d4fb1af850a622fe3508072 I'm no longer able to reproduce the minimal bug report I made in https://github.com/rstudio/rstudio/issues/1920 

And, so far, no errors when developing the more complex **fstArray** within RStudio (https://github.com/fstpackage/fst/issues/109#issuecomment-350766435)

**Comment by thierrygosselin** [comment] 2018-01-22 22:58
Hi @MarcusKlik problem solved on my end!

**Comment by MarcusKlik** [comment] 2018-01-23 08:44
That's great, thanks for testing at such short notice!!!

Apparently, no method from the OpenMP library can be used from a fork on macOS. This fix will solve a couple of other issues as well 👍 

Nice work guys, thanks!

**Closed as completed by MarcusKlik** 2018-01-23 08:44 UTC
Labels: bug
