### ISSUE TITLE
install failure, reinstall of R and fst

### ISSUE THREAD

**Issue by iwelch** [fstpackage/fst#258] opened 2021-04-21 19:53 UTC
latest R 4.0.5:

```
Error: package or namespace load failed for ‘fst’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/fst/libs/fst.so':
  dlopen(/usr/local/lib/R/4.0/site-library/fst/libs/fst.so, 6): Symbol not found: _XXH32
  Referenced from: /usr/local/lib/R/4.0/site-library/fst/libs/fst.so
  Expected in: flat namespace
 in /usr/local/lib/R/4.0/site-library/fst/libs/fst.so
Error: loading failed
use traceback() to see the error line
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/4.0/site-library/fst/libs/fst.so':
  dlopen(/usr/local/lib/R/4.0/site-library/fst/libs/fst.so, 6): Symbol not found: _XXH32
  Referenced from: /usr/local/lib/R/4.0/site-library/fst/libs/fst.so
  Expected in: flat namespace
 in /usr/local/lib/R/4.0/site-library/fst/libs/fst.so
Calls: <Anonymous> ... <Anonymous> -> loadNamespace -> library.dynam -> dyn.load
```

**Comment by rodonn** [comment] 2021-05-27 17:41
I'm running into the same error on R 4.1.0

I'm using OSX 11.3.1 (20E241)

I tried `install.packages('fst')` as well as 
`devtools::install_github("fstPackage/fst", ref = "develop")`

**Comment by rodonn** [comment] 2021-05-27 18:09
duplicate of #250

**Comment by rodonn** [comment] 2021-05-27 18:09
Duplicate of #250

**Comment by MarcusKlik** [comment] 2022-02-11 12:33
Hi @iwelch, the `macOS` linking problems should be solved with the latest release. The problem was that both `LZ4` and `ZSTD` contain code for `xxhash`, but the implementation versions were not identical! I believe `Makevars` is now configured correctly to avoid these linking problems (also see the [github workflow](https://github.com/fstpackage/fst/actions/runs/1828877491))

thanks for reporting!

**Closed as completed by MarcusKlik** 2022-02-11 12:33 UTC
